# models.pyi
from typing import Optional
import datetime


class StatusLevel:
    def __init__(self, statusObj, level_num): ...

    # ----- Date columns -----

    def get_baseline_start(self) -> Optional[datetime.date]: ...
    def get_baseline_start_formatted(self) -> str: ...

    def get_baseline_finish(self) -> Optional[datetime.date]: ...
    def get_baseline_finish_formatted(self) -> str: ...

    def get_actual_start(self) -> Optional[datetime.date]: ...
    def get_actual_start_formatted(self) -> str: ...

    def get_actual_finish(self) -> Optional[datetime.date]: ...
    def get_actual_finish_formatted(self) -> str: ...

    def get_expected_finish(self) -> Optional[datetime.date]: ...
    def get_expected_finish_formatted(self) -> str: ...

    # ----- Percentage columns -----

    def get_actual_percent_complete(self) -> Optional[float]: ...
    def get_actual_percent_complete_formatted(self) -> str: ...

    def get_expected_percent_complete(self) -> Optional[float]: ...
    def get_expected_percent_complete_formatted(self) -> str: ...

    # ----- String columns -----

    def get_status(self) -> str: ...
    def get_description(self) -> str: ...
